name: fin_tamer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  intl: ^0.20.2

  go_router: ^15.1.2
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0

  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  spoiler_widget: ^1.0.12
  sensors_plus: ^6.1.1
  shake_gesture: ^1.2.0
  collection: ^1.19.1
  fuzzywuzzy: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  build_runner: ^2.5.2
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
