name: fin_tamer
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  chart_widget:
    path: ./chart_widget

  collection: ^1.19.1
  dio: ^5.4.0
  logger: ^2.0.2+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  fuzzywuzzy: ^1.2.0
  go_router: ^15.1.2
  intl: ^0.20.2
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  path_provider: ^2.1.1
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  sensors_plus: ^6.1.1
  shake_gesture: ^1.2.0
  spoiler_widget: ^1.0.12
  worker_manager: ^7.2.6
  internet_connection_checker: ^3.0.1
  shared_preferences: ^2.5.3
  flutter_colorpicker: ^1.1.0
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.7

dev_dependencies:
  build_runner: ^2.5.2
  custom_lint: ^0.7.5
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  objectbox_generator: ^4.3.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  patrol: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/favicon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff" # Цвет фона (можно заменить на свой)
  image: assets/images/splash.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleToFill

patrol:
  app_name: My App
  android:
    package_name: com.example.myapp
  ios:
    bundle_id: com.example.MyApp
