// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/event_sourcing/sync_event.dart';
import 'features/account/data/local/entities/account_entity.dart';
import 'features/account/data/local/entities/stat_item_entity.dart';
import 'features/category/data/local/entities/category_entity.dart';
import 'features/history/data/local/entities/history_entity.dart';
import 'features/transaction/data/local/entities/transaction_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 7272498888885002791),
    name: 'CategoryEntity',
    lastPropertyId: const obx_int.IdUid(5, 2164722955887051621),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4991616021255689001),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7279879373140819955),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1452561443527565598),
        name: 'emoji',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5572852441722186374),
        name: 'isIncome',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2164722955887051621),
        name: 'apiId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 7951609919812821731),
    name: 'HistoryEntity',
    lastPropertyId: const obx_int.IdUid(8, 27775157830502293),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4023632695592437656),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3960312945438535773),
        name: 'apiId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6929800089414226823),
        name: 'accountId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9043974459244823721),
        name: 'changeType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 725969776815586734),
        name: 'previousStateJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6549160774005160476),
        name: 'newStateJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 325875762559090582),
        name: 'changeTimestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 27775157830502293),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 3218171980000344758),
    name: 'AccountEntity',
    lastPropertyId: const obx_int.IdUid(9, 7502156885642015775),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2634608706535449416),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4644545482946923430),
        name: 'apiId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3242103203123592301),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1773618268272246912),
        name: 'balance',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7858932498738227295),
        name: 'currency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1995406758587971667),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7502156885642015775),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 7419752769170049923),
    name: 'StatItemEntity',
    lastPropertyId: const obx_int.IdUid(11, 8455360228724349651),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5702036449626325574),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1347678859445470119),
        name: 'apiId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2718226763762621476),
        name: 'accountApiId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3501366388118049952),
        name: 'isIncome',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6732556694054994663),
        name: 'categoryId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2011934168724031218),
        name: 'categoryName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7727764499745813961),
        name: 'emoji',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8455360228724349651),
        name: 'amount',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 7913135380541029049),
    name: 'TransactionEntity',
    lastPropertyId: const obx_int.IdUid(11, 2441127887163230469),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8710773663591771476),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7748649751561391004),
        name: 'apiId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6883603647684010312),
        name: 'accountApiId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1263007903486449490),
        name: 'categoryApiId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6850583749076550394),
        name: 'amount',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8187690267295782108),
        name: 'transactionDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8086552041661888079),
        name: 'comment',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2173491501105075079),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2795732724551334393),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8229074962202376406),
        name: 'accountId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2441127887163230469),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 3261602400766834220),
    name: 'SyncEvent',
    lastPropertyId: const obx_int.IdUid(6, 8744715383352343588),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6406197369498130577),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 107547474130071092),
        name: 'entityTypeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1434243693414712345),
        name: 'eventTypeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1109140077375292495),
        name: 'entityId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6403648093323011210),
        name: 'payloadJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8744715383352343588),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(8, 3261602400766834220),
    lastIndexId: const obx_int.IdUid(1, 2005279266660496490),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [4184324922779376647, 4997635429375364018],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      6067831564966800248,
      2409324048533550071,
      5931921984227595126,
      6401017984614174097,
      7227130836619366336,
      3501817314430306865,
      3723387938336280827,
      8869011092584133625,
      9128953702729066187,
      1847400823823542275,
      1645820557717940178,
      3733016997206402289,
      6922564085595008223,
      5957917243085841111,
      5372237746619062107,
      8685277185981112531,
      5316522730820120505,
      5862021724767335644,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CategoryEntity: obx_int.EntityDefinition<CategoryEntity>(
      model: _entities[0],
      toOneRelations: (CategoryEntity object) => [],
      toManyRelations: (CategoryEntity object) => {},
      getId: (CategoryEntity object) => object.id,
      setId: (CategoryEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CategoryEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final emojiOffset = fbb.writeString(object.emoji);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, emojiOffset);
        fbb.addBool(3, object.isIncome);
        fbb.addInt64(4, object.apiId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final apiIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final emojiParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final isIncomeParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final object = CategoryEntity(
          id: idParam,
          apiId: apiIdParam,
          name: nameParam,
          emoji: emojiParam,
          isIncome: isIncomeParam,
        );

        return object;
      },
    ),
    HistoryEntity: obx_int.EntityDefinition<HistoryEntity>(
      model: _entities[1],
      toOneRelations: (HistoryEntity object) => [],
      toManyRelations: (HistoryEntity object) => {},
      getId: (HistoryEntity object) => object.id,
      setId: (HistoryEntity object, int id) {
        object.id = id;
      },
      objectToFB: (HistoryEntity object, fb.Builder fbb) {
        final changeTypeOffset = fbb.writeString(object.changeType);
        final previousStateJsonOffset = fbb.writeString(
          object.previousStateJson,
        );
        final newStateJsonOffset = fbb.writeString(object.newStateJson);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.apiId);
        fbb.addInt64(2, object.accountId);
        fbb.addOffset(3, changeTypeOffset);
        fbb.addOffset(4, previousStateJsonOffset);
        fbb.addOffset(5, newStateJsonOffset);
        fbb.addInt64(6, object.changeTimestamp.millisecondsSinceEpoch);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final apiIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final accountIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final changeTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final previousStateJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final newStateJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final changeTimestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final object = HistoryEntity(
          id: idParam,
          apiId: apiIdParam,
          accountId: accountIdParam,
          changeType: changeTypeParam,
          previousStateJson: previousStateJsonParam,
          newStateJson: newStateJsonParam,
          changeTimestamp: changeTimestampParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
    AccountEntity: obx_int.EntityDefinition<AccountEntity>(
      model: _entities[2],
      toOneRelations: (AccountEntity object) => [],
      toManyRelations: (AccountEntity object) => {},
      getId: (AccountEntity object) => object.id,
      setId: (AccountEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AccountEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final balanceOffset = fbb.writeString(object.balance);
        final currencyOffset = fbb.writeString(object.currency);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.apiId);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, balanceOffset);
        fbb.addOffset(4, currencyOffset);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final apiIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final balanceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final currencyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final object = AccountEntity(
          id: idParam,
          apiId: apiIdParam,
          name: nameParam,
          balance: balanceParam,
          currency: currencyParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        );

        return object;
      },
    ),
    StatItemEntity: obx_int.EntityDefinition<StatItemEntity>(
      model: _entities[3],
      toOneRelations: (StatItemEntity object) => [],
      toManyRelations: (StatItemEntity object) => {},
      getId: (StatItemEntity object) => object.id,
      setId: (StatItemEntity object, int id) {
        object.id = id;
      },
      objectToFB: (StatItemEntity object, fb.Builder fbb) {
        final categoryNameOffset = fbb.writeString(object.categoryName);
        final emojiOffset = fbb.writeString(object.emoji);
        final amountOffset = fbb.writeString(object.amount);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.apiId);
        fbb.addInt64(2, object.accountApiId);
        fbb.addBool(6, object.isIncome);
        fbb.addInt64(7, object.categoryId);
        fbb.addOffset(8, categoryNameOffset);
        fbb.addOffset(9, emojiOffset);
        fbb.addOffset(10, amountOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final apiIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final accountApiIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final isIncomeParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final categoryIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final categoryNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final emojiParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final amountParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final object = StatItemEntity(
          id: idParam,
          apiId: apiIdParam,
          accountApiId: accountApiIdParam,
          isIncome: isIncomeParam,
          categoryId: categoryIdParam,
          categoryName: categoryNameParam,
          emoji: emojiParam,
          amount: amountParam,
        );

        return object;
      },
    ),
    TransactionEntity: obx_int.EntityDefinition<TransactionEntity>(
      model: _entities[4],
      toOneRelations: (TransactionEntity object) => [],
      toManyRelations: (TransactionEntity object) => {},
      getId: (TransactionEntity object) => object.id,
      setId: (TransactionEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TransactionEntity object, fb.Builder fbb) {
        final amountOffset = fbb.writeString(object.amount);
        final commentOffset = object.comment == null
            ? null
            : fbb.writeString(object.comment!);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.apiId);
        fbb.addInt64(2, object.accountApiId);
        fbb.addInt64(3, object.categoryApiId);
        fbb.addOffset(4, amountOffset);
        fbb.addInt64(5, object.transactionDate.millisecondsSinceEpoch);
        fbb.addOffset(6, commentOffset);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(9, object.accountId);
        fbb.addBool(10, object.isDeleted);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final apiIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final accountIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final accountApiIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final categoryApiIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final amountParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final transactionDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final commentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          24,
          false,
        );
        final object = TransactionEntity(
          id: idParam,
          apiId: apiIdParam,
          accountId: accountIdParam,
          accountApiId: accountApiIdParam,
          categoryApiId: categoryApiIdParam,
          amount: amountParam,
          transactionDate: transactionDateParam,
          comment: commentParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          isDeleted: isDeletedParam,
        );

        return object;
      },
    ),
    SyncEvent: obx_int.EntityDefinition<SyncEvent>(
      model: _entities[5],
      toOneRelations: (SyncEvent object) => [],
      toManyRelations: (SyncEvent object) => {},
      getId: (SyncEvent object) => object.id,
      setId: (SyncEvent object, int id) {
        object.id = id;
      },
      objectToFB: (SyncEvent object, fb.Builder fbb) {
        final entityIdOffset = fbb.writeString(object.entityId);
        final payloadJsonOffset = fbb.writeString(object.payloadJson);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.entityTypeIndex);
        fbb.addInt64(2, object.eventTypeIndex);
        fbb.addOffset(3, entityIdOffset);
        fbb.addOffset(4, payloadJsonOffset);
        fbb.addInt64(5, object.timestamp.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final entityTypeIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final eventTypeIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final entityIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final payloadJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final object = SyncEvent(
          id: idParam,
          entityTypeIndex: entityTypeIndexParam,
          eventTypeIndex: eventTypeIndexParam,
          entityId: entityIdParam,
          payloadJson: payloadJsonParam,
          timestamp: timestampParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CategoryEntity] entity fields to define ObjectBox queries.
class CategoryEntity_ {
  /// See [CategoryEntity.id].
  static final id = obx.QueryIntegerProperty<CategoryEntity>(
    _entities[0].properties[0],
  );

  /// See [CategoryEntity.name].
  static final name = obx.QueryStringProperty<CategoryEntity>(
    _entities[0].properties[1],
  );

  /// See [CategoryEntity.emoji].
  static final emoji = obx.QueryStringProperty<CategoryEntity>(
    _entities[0].properties[2],
  );

  /// See [CategoryEntity.isIncome].
  static final isIncome = obx.QueryBooleanProperty<CategoryEntity>(
    _entities[0].properties[3],
  );

  /// See [CategoryEntity.apiId].
  static final apiId = obx.QueryIntegerProperty<CategoryEntity>(
    _entities[0].properties[4],
  );
}

/// [HistoryEntity] entity fields to define ObjectBox queries.
class HistoryEntity_ {
  /// See [HistoryEntity.id].
  static final id = obx.QueryIntegerProperty<HistoryEntity>(
    _entities[1].properties[0],
  );

  /// See [HistoryEntity.apiId].
  static final apiId = obx.QueryIntegerProperty<HistoryEntity>(
    _entities[1].properties[1],
  );

  /// See [HistoryEntity.accountId].
  static final accountId = obx.QueryIntegerProperty<HistoryEntity>(
    _entities[1].properties[2],
  );

  /// See [HistoryEntity.changeType].
  static final changeType = obx.QueryStringProperty<HistoryEntity>(
    _entities[1].properties[3],
  );

  /// See [HistoryEntity.previousStateJson].
  static final previousStateJson = obx.QueryStringProperty<HistoryEntity>(
    _entities[1].properties[4],
  );

  /// See [HistoryEntity.newStateJson].
  static final newStateJson = obx.QueryStringProperty<HistoryEntity>(
    _entities[1].properties[5],
  );

  /// See [HistoryEntity.changeTimestamp].
  static final changeTimestamp = obx.QueryDateProperty<HistoryEntity>(
    _entities[1].properties[6],
  );

  /// See [HistoryEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<HistoryEntity>(
    _entities[1].properties[7],
  );
}

/// [AccountEntity] entity fields to define ObjectBox queries.
class AccountEntity_ {
  /// See [AccountEntity.id].
  static final id = obx.QueryIntegerProperty<AccountEntity>(
    _entities[2].properties[0],
  );

  /// See [AccountEntity.apiId].
  static final apiId = obx.QueryIntegerProperty<AccountEntity>(
    _entities[2].properties[1],
  );

  /// See [AccountEntity.name].
  static final name = obx.QueryStringProperty<AccountEntity>(
    _entities[2].properties[2],
  );

  /// See [AccountEntity.balance].
  static final balance = obx.QueryStringProperty<AccountEntity>(
    _entities[2].properties[3],
  );

  /// See [AccountEntity.currency].
  static final currency = obx.QueryStringProperty<AccountEntity>(
    _entities[2].properties[4],
  );

  /// See [AccountEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<AccountEntity>(
    _entities[2].properties[5],
  );

  /// See [AccountEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<AccountEntity>(
    _entities[2].properties[6],
  );
}

/// [StatItemEntity] entity fields to define ObjectBox queries.
class StatItemEntity_ {
  /// See [StatItemEntity.id].
  static final id = obx.QueryIntegerProperty<StatItemEntity>(
    _entities[3].properties[0],
  );

  /// See [StatItemEntity.apiId].
  static final apiId = obx.QueryIntegerProperty<StatItemEntity>(
    _entities[3].properties[1],
  );

  /// See [StatItemEntity.accountApiId].
  static final accountApiId = obx.QueryIntegerProperty<StatItemEntity>(
    _entities[3].properties[2],
  );

  /// See [StatItemEntity.isIncome].
  static final isIncome = obx.QueryBooleanProperty<StatItemEntity>(
    _entities[3].properties[3],
  );

  /// See [StatItemEntity.categoryId].
  static final categoryId = obx.QueryIntegerProperty<StatItemEntity>(
    _entities[3].properties[4],
  );

  /// See [StatItemEntity.categoryName].
  static final categoryName = obx.QueryStringProperty<StatItemEntity>(
    _entities[3].properties[5],
  );

  /// See [StatItemEntity.emoji].
  static final emoji = obx.QueryStringProperty<StatItemEntity>(
    _entities[3].properties[6],
  );

  /// See [StatItemEntity.amount].
  static final amount = obx.QueryStringProperty<StatItemEntity>(
    _entities[3].properties[7],
  );
}

/// [TransactionEntity] entity fields to define ObjectBox queries.
class TransactionEntity_ {
  /// See [TransactionEntity.id].
  static final id = obx.QueryIntegerProperty<TransactionEntity>(
    _entities[4].properties[0],
  );

  /// See [TransactionEntity.apiId].
  static final apiId = obx.QueryIntegerProperty<TransactionEntity>(
    _entities[4].properties[1],
  );

  /// See [TransactionEntity.accountApiId].
  static final accountApiId = obx.QueryIntegerProperty<TransactionEntity>(
    _entities[4].properties[2],
  );

  /// See [TransactionEntity.categoryApiId].
  static final categoryApiId = obx.QueryIntegerProperty<TransactionEntity>(
    _entities[4].properties[3],
  );

  /// See [TransactionEntity.amount].
  static final amount = obx.QueryStringProperty<TransactionEntity>(
    _entities[4].properties[4],
  );

  /// See [TransactionEntity.transactionDate].
  static final transactionDate = obx.QueryDateProperty<TransactionEntity>(
    _entities[4].properties[5],
  );

  /// See [TransactionEntity.comment].
  static final comment = obx.QueryStringProperty<TransactionEntity>(
    _entities[4].properties[6],
  );

  /// See [TransactionEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<TransactionEntity>(
    _entities[4].properties[7],
  );

  /// See [TransactionEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<TransactionEntity>(
    _entities[4].properties[8],
  );

  /// See [TransactionEntity.accountId].
  static final accountId = obx.QueryIntegerProperty<TransactionEntity>(
    _entities[4].properties[9],
  );

  /// See [TransactionEntity.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<TransactionEntity>(
    _entities[4].properties[10],
  );
}

/// [SyncEvent] entity fields to define ObjectBox queries.
class SyncEvent_ {
  /// See [SyncEvent.id].
  static final id = obx.QueryIntegerProperty<SyncEvent>(
    _entities[5].properties[0],
  );

  /// See [SyncEvent.entityTypeIndex].
  static final entityTypeIndex = obx.QueryIntegerProperty<SyncEvent>(
    _entities[5].properties[1],
  );

  /// See [SyncEvent.eventTypeIndex].
  static final eventTypeIndex = obx.QueryIntegerProperty<SyncEvent>(
    _entities[5].properties[2],
  );

  /// See [SyncEvent.entityId].
  static final entityId = obx.QueryStringProperty<SyncEvent>(
    _entities[5].properties[3],
  );

  /// See [SyncEvent.payloadJson].
  static final payloadJson = obx.QueryStringProperty<SyncEvent>(
    _entities[5].properties[4],
  );

  /// See [SyncEvent.timestamp].
  static final timestamp = obx.QueryDateProperty<SyncEvent>(
    _entities[5].properties[5],
  );
}
